### ISSUE TITLE
include(PARAVIEW_USE_FILE) fails with paraview 5.7

### ISSUE THREAD

**Issue by pletzer** [tinyendian/lfric_reader#2]
Hi,

I built paraview from source on Mac OS X (latest from github) and I'm getting 

(base) niwa-1019500~/lfric_reader/src/cxx/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/paraview/
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found OpenGL: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework  found components: OpenGL 
CMake Deprecation Warning at /usr/local/paraview/lib/cmake/paraview-5.8/paraview-use-file-deprecated.cmake:1 (message):
  The `PARAVIEW_USE_FILE` is no longer used starting with 5.7.
Call Stack (most recent call first):
  CMakeLists.txt:18 (INCLUDE)

CMake Error at CMakeLists.txt:26 (ADD_PARAVIEW_PLUGIN):
  Unknown CMake command "ADD_PARAVIEW_PLUGIN".

-- Configuring incomplete, errors occurred!

**Comment by tinyendian** [comment]
Hi @pletzer ,

It seems that the CMakeLists.txt format has changed with ParaView 5.7, I haven't built the plugin with this most recent version of ParaView yet. Please have a look here for the changes that are needed: [](https://kitware.github.io/paraview-docs/nightly/cxx/PluginHowto.html), section "Compiling into a Shared Library".

**Comment by tinyendian** [comment]
Hi @pletzer the build system and plugin code are now upgraded to work with ParaView v5.7 and later, I tested with v5.7 and v5.8. I'll close this issue for now - let me know if it still doesn't work.

**Comment by pletzer** [comment]
Thanks, fixed!
